### ISSUE TITLE
[Beta] LSFMD objects

### ISSUE THREAD

**Issue by DKnowlesSARP** [gtasarp/samp-public#110]
General Information (evidence, etc): 
 1. Two ground objects overlapping on the floor - making it look ugly.
![sa-mp-008](https://f.cloud.github.com/assets/5796184/1421858/feea9a00-3ff2-11e3-9505-d111c11726b8.png)
![sa-mp-009](https://f.cloud.github.com/assets/5796184/1421859/feec8e46-3ff2-11e3-9a40-6d02d8d2f12d.png)

 2. Invisible object + objects that you can walk through

http://www.youtube.com/watch?v=ECycTMj_bnE&feature=youtu.be
(video unlisted). 
![sa-mp-011](https://f.cloud.github.com/assets/5796184/1422524/c9691fdc-3ffc-11e3-84ba-534192267ac9.png)
![sa-mp-012](https://f.cloud.github.com/assets/5796184/1422525/c96ae9de-3ffc-11e3-85d7-d5066f25821f.png)
How does the bug harm the server?: Doesn't really 'harm' as such, just makes it look ugly.
Did anyone assist with you with handling the bug? If so, who?: Watson, Tia.

**Comment by iiNzTicTx** [comment]
There's a new HQ for them.
