### ISSUE TITLE
[Onbeta] /mdc bugs

### ISSUE THREAD

**Issue by MichaelWatsonSARP** [gtasarp/samp-public#111]
1.
General information (evidence, etc): LSFMD can use /mdc
How does the bug harm the server?: -
Did anyone assist you with handling the bug? If so, who?: No.

2.
General information (evidence, etc): If you /mdc, then 'Trace Phone' it will either track everybody on the server(including you) or not work, generaly bugged
![sa-mp-479](https://f.cloud.github.com/assets/4933946/1422051/f18c57c4-3ff5-11e3-98e1-0fd8363c3e32.png)
How does the bug harm the server?: -
Did anyone assist you with handling the bug? If so, who?: No.

3.
https://github.com/gtasarp/samp-public/issues/113

4.
/mdc -> Database -> Information
Instead of using the full name it uses the name I typed in(or id):
![sa-mp-486](https://f.cloud.github.com/assets/4933946/1423903/fc07875a-4013-11e3-8e55-0645c149e115.png)

**Comment by iiNzTicTx** [comment]
New MDC was implemented.
