### ISSUE TITLE
Interior bug to DeMorgan.

### ISSUE THREAD

**Issue by VinnyMeadows** [gtasarp/samp-public#129]
General information (evidence, etc): I noticed no one reported this so I'm just going to slide this in here. 
http://www.gta-sarp.com/forums/showthread.php?95104-kriz-ways-s-Bug-Report-Fort-Carson-Canteen-Bug

How does the bug harm the server?: You can easily access DeMorgan and troll/fuck shit up.

Did anyone assist you with handling the bug? If so, who?: Bug reported by Kriz Ways.

**Comment by iiNzTicTx** [comment]
They have a new one. Closed.
