### ISSUE TITLE
Skin glitch problem  (Please Help)

### ISSUE THREAD

**Issue by Morsii** [gtasarp/samp-public#149]
So I have this problem: I got a skin glitch when you log, crash, die anything etc.
My skin gets change to this random Taekwondo Guy skin and removes my character's skin
So It's really annoying that I have to go change it everytime.
It also changes my faction/family's skin so it's really frustrating
Please If you can do something about it, tell me and help me solve it please.
I got an Alt and it's working fine, so it's a problem with this account I am using.
So I'm thinking if an admin can send and give all my stuff to a new account to solve this.

**Comment by ThatGuyKalvin** [comment]
fix was applied
