### ISSUE TITLE
ban bug

### ISSUE THREAD

**Issue by Pr0kKiLlEr** [gtasarp/samp-public#153]
in game name:many but got banned from Ronald_Casper acc
i got dmed by a guy lost everything(had brass knuckles too)
when i went to hospital i got banned for hacked brass knuckles
well i didn't hack i was in hospital after dm and got banned
plz unban
ty for support
Ronald_Casper
Michael_Rambo
Claudie_Speed
these are my in game names :P

**Comment by Pr0kKiLlEr** [comment]
plz i say the truth unban and give weapons back i lost from dmer

**Comment by GeorgeMichael1** [comment]
i have the same problem i was in jail and im banned i have no idea why im banned please unban me my account id is George_Michael
