### ISSUE TITLE
 /q while in death animation.

### ISSUE THREAD

**Issue by DakotaHardieSARP** [gtasarp/samp-public#154]
General information (evidence, etc):
Basically, /q'ing or any form of logging out while you are in the death animation will cause you to respawn with about 5HP, there are alot of newbs abusing this to DM and come back OVER and OVER again.

How does the bug harm the server?: It's a pretty bad and annoying bug.
Did anyone assist you with handling the bug? If so, who?: None.

**Comment by ThatGuyKalvin** [comment]
Fixed
