### ISSUE TITLE
Drivers License

### ISSUE THREAD

**Issue by Hexatomic** [gtasarp/samp-public#155]
Hi there,

Everytime I try to sit my drivers license, I get a frozen flashing screen forcing me to quit out of client, and then when I log back in it's taken my money but I don't have a license. Ways to fix this problem?

![sa-mp-001](https://cloud.githubusercontent.com/assets/11804993/6996408/fe94cff0-dbda-11e4-9dc8-74794ad2d222.png)

**Comment by ThatGuyKalvin** [comment]
Issue with world boundaries by the looks of things...
Not sure if it's just you or not, I suggest showing this to an admin to get your license.
