### ISSUE TITLE
I got banned for something i didnt do called ''Shotgun hacking''

### ISSUE THREAD

**Issue by Korv1** [gtasarp/samp-public#163]
Well i was playing as an arms dealer and i made a shotgun for me and i made it everytime i died to so one time when i was in a shootout with 2 ppl i got killed and i spawned in it said that my shotgun got removed and i pressed OK and then i got banned so i have no clue why this happend and i havent ''shotgun hacked''

**Comment by Korv1** [comment]
IG name:Izaak_Knox

**Comment by Korv1** [comment]
I think my password has been changed for  some reason

2015-08-19 23:46 GMT+02:00 Kalvin <notifications@github.com>:

**Comment by ThatGuyKalvin** [comment]
http://www.gta-sarp.com/forums/forms.php?do=form&fid=91
Post proof of your account ownership then an Executive will reset your password.
