### ISSUE TITLE
Doors bug

### ISSUE THREAD

**Issue by BatmanSkadoo** [gtasarp/samp-public#87]
General information (evidence, etc): Ehh.. When you 'F' at a door (FBI's in this case) you go through the wall.. Although it's known, it should be placed here. I went through the bug reports and didn't see this one.
How does the bug harm the server?:  Unauthorized access to private areas.
Did anyone assist you with handling the bug? If so, who?: Nope.

**Comment by ThatGuyKalvin** [comment]
That's not it 0_o anyway I'll look into restricting the FBI directors button
